services:
  gateway:
    build: services/gateway
    ports:
      - "5000:8080"
    depends_on:
      - search
      - profile
  search:
    build: services/search
    depends_on:
      - geo
      - rate
  profile:
    build: services/profile
  geo:
    build: services/geo
  rate:
    build: services/rate
