services:
  frontend:
    build: .
    entrypoint: go-micro-services frontend
    ports:
      - "5000:8080"
    depends_on:
      - search
      - profile
  search:
    build: .
    entrypoint: go-micro-services search
    links:
      - geo
      - rate
  profile:
    build: .
    entrypoint: go-micro-services profile
    links:
      - geo
      - rate
  geo:
    build: .
    entrypoint: go-micro-services geo
  rate:
    build: .
    entrypoint: go-micro-services rate
