services:
  gateway:
    build: .
    entrypoint: /app/go-micro-services gateway
    ports:
      - "5000:8080"
    depends_on:
      - search
      - profile
  search:
    build: .
    entrypoint: /app/go-micro-services search
    depends_on:
      - geo
      - rate
  profile:
    build: .
    entrypoint: /app/go-micro-services profile
  geo:
    build: .
    entrypoint: /app/go-micro-services geo
  rate:
    build: .
    entrypoint: /app/go-micro-services rate
