on:
  push:
    branches:
    - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: docker/login-action@v2 
        name: Log in to the Container registry
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GH_PACKAGE_ACCOUNT }}
          password: ${{ secrets.GH_PACKAGE_TOKEN }}

      - uses: actions-hub/docker/cli@master 
        name: Use Docker-CLI
        env:
          SKIP_LOGIN: true

      - name: Build & Push
        run: |
          sudo docker-compose build
          sudo docker-compose push
